WIP: GHC-9.2 compatibility (#305)
With this commit, based on Ryan Scott's patch, building with
```
cabal v1-install --enable-tests --allow-newer=hsc2hs:base --allow-newer=ghc-paths:Cabal
cabal v1-test
```
the tests pass except for the `TemplateHaskell` ones (see below).
This could be due to some commented out code in `src/Extract.hs`,
cutting out the type-checking phase:
```diff
-  mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods
+  --mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods

-  let sortedMods = flattenSCCs (topSortModuleGraph False mods' Nothing)
-  reverse <$> mapM (loadModPlugins >=> parseModule >=> typecheckModule >=> loadModule) sortedMods
+  let sortedMods = flattenSCCs
+#if __GLASGOW_HASKELL__ >= 901
+                     $ filterToposortToModules
+#endif
+                     $ topSortModuleGraph False mods Nothing
+  reverse <$> mapM (loadModPlugins >=> parseModule) sortedMods
```

Test failure:
```
test/extract/th/Foo.hs:8:7: warning: [-Woperator-whitespace-ext-conflict]
    The prefix use of a ‘$’ would denote an untyped splice
      were the TemplateHaskell extension enabled.
    Suggested fix: add whitespace after the ‘$’.
  |
8 | foo = $(bar)
  |       ^

test/extract/th/Foo.hs:8:7: error:
    parse error on input ‘$’
    Perhaps you intended to use TemplateHaskell
  |
8 | foo = $(bar)
  |       ^

Failures:

  test/ExtractSpec.hs:91:5:
  1) Extract, extract (regression tests), works with a module that splices in an expression from an other module
       uncaught exception: ExitCode
       ExitFailure 1

  To rerun use: --match "/Extract/extract (regression tests)/works with a module that splices in an expression from an other module/"

Randomized with seed 107198347
```